# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

require 'google/protobuf'


descriptor_data = "\n\x0c\x63ommon.proto\x12\x16\x63om.gpch.grpc.protobuf\"\xb4\x01\n\x1cValidateTokenPositionRequest\x12.\n\x04lang\x18\x01 \x01(\x0e\x32 .com.gpch.grpc.protobuf.Language\x12\x17\n\x0ftaskInTTLFormat\x18\x02 \x01(\t\x12\x34\n\rstudentAnswer\x18\x03 \x03(\x0b\x32\x1d.com.gpch.grpc.protobuf.Token\x12\x15\n\rwordsToSelect\x18\x04 \x03(\t\"\xb4\x01\n\x1dValidateTokenPositionResponse\x12-\n\x06\x65rrors\x18\x01 \x03(\x0b\x32\x1d.com.gpch.grpc.protobuf.Error\x12\x17\n\x0ftaskInTTLFormat\x18\x02 \x01(\t\x12\x34\n\rstudentAnswer\x18\x03 \x03(\x0b\x32\x1d.com.gpch.grpc.protobuf.Token\x12\x15\n\rwordsToSelect\x18\x04 \x03(\t\".\n\x13GetTaskSetupRequest\x12\x17\n\x0ftaskInTTLFormat\x18\x01 \x01(\t\"\x9d\x01\n\x14GetTaskSetupResponse\x12\x0c\n\x04task\x18\x01 \x01(\t\x12H\n\x06tokens\x18\x02 \x03(\x0b\x32\x38.com.gpch.grpc.protobuf.GetTaskSetupResponse.TokensEntry\x1a-\n\x0bTokensEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\x05Token\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"9\n\x05\x45rror\x12\x30\n\x05\x65rror\x18\x01 \x03(\x0b\x32!.com.gpch.grpc.protobuf.ErrorPart\"\'\n\tErrorPart\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t*\x1a\n\x08Language\x12\x06\n\x02RU\x10\x00\x12\x06\n\x02\x45N\x10\x01\x32\x8e\x02\n\x16SentenceCheckerService\x12\x86\x01\n\x15ValidateTokenPosition\x12\x34.com.gpch.grpc.protobuf.ValidateTokenPositionRequest\x1a\x35.com.gpch.grpc.protobuf.ValidateTokenPositionResponse\"\x00\x12k\n\x0cGetTaskSetup\x12+.com.gpch.grpc.protobuf.GetTaskSetupRequest\x1a,.com.gpch.grpc.protobuf.GetTaskSetupResponse\"\x00\x42\x02P\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Com
  module Gpch
    module Grpc
      module Protobuf
        ValidateTokenPositionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.gpch.grpc.protobuf.ValidateTokenPositionRequest").msgclass
        ValidateTokenPositionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.gpch.grpc.protobuf.ValidateTokenPositionResponse").msgclass
        GetTaskSetupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.gpch.grpc.protobuf.GetTaskSetupRequest").msgclass
        GetTaskSetupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.gpch.grpc.protobuf.GetTaskSetupResponse").msgclass
        Token = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.gpch.grpc.protobuf.Token").msgclass
        Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.gpch.grpc.protobuf.Error").msgclass
        ErrorPart = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.gpch.grpc.protobuf.ErrorPart").msgclass
        Language = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.gpch.grpc.protobuf.Language").enummodule
      end
    end
  end
end
